export const projects = [
  {
    title: "Buscador de Cep",
    img: "/imagens/baixados.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-react"],
    github: "https://github.com/AleMiclos/buscador-cep",
    site: "https://buscador-cep-steel.vercel.app/",
  },
  {
    title: "Login Page",
    img: "/imagens/loginpage.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-js", "fa-brands fa-angular"],
    github: "https://github.com/AleMiclos/LoginPage",
    site: "https://login-page-three-bay.vercel.app/login",
  },
  {
    title: "Game Score",
    img: "/imagens/gamescore.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-js"],
    github: "https://github.com/AleMiclos/JogoDaNave",
    site: "https://jogo-da-nave-tan.vercel.app/",
  },
  {
    title: "Genius Game",
    img: "/imagens/genio.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-js"],
    github: "https://github.com/AleMiclos/geniusgame",
    site: "https://geniusgame-theta.vercel.app/",
  },
  {
    title: "Landing Page",
    img: "/imagens/landingPage.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-vuejs"],
    github: "https://github.com/AleMiclos/LandingPageTeste",
    site: "https://landing-page-teste-xi.vercel.app/",
  },
  {
    title: "Tabela React",
    img: "/imagens/tabela.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-react"],
    github: "https://github.com/AleMiclos/geniusgame",
    site: "https://tabela-react-js.vercel.app/",
  },
  {
    title: "Novo projeto em breve",
    img: "/imagens/embreve.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-react"],
    github: "",
    site: "",
  },
  {
    title: "Novo projeto em breve",
    img: "/imagens/embreve.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-react"],
     github: "",
    site: "",
  },
  {
    title: "Novo projeto em breve",
    img: "/imagens/embreve.png",
    techs: ["fa-brands fa-html5", "fa-brands fa-css3-alt", "fa-brands fa-react"],
    github: "",
    site: "",
  },
];
